;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ido-switch-buffer
        ignore
        indent-for-tab-command
        kill-region
        mouse-drag-header-line
        mouse-select-window
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        helm-M-x
        ido-find-file
        js2-down-mouse-3
        js2-mode-show-node
        magit-status
        mouse-save-then-kill
        mouse-set-region
        shk-tabbar-prev
        tabbar-select-tab-callback
        ))
