;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ignore
        kill-region
        mouse-drag-header-line
        mouse-select-window
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        ido-find-file
        js2-mode-show-node
        mouse-save-then-kill
        shk-tabbar-prev
        tabbar-select-tab-callback
        ))
